---
title: "Frecuencia Relativa"
author: "Fermín Acosta"
date: "11/11/2018"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

En este archivo se simula el lanzamiento de un dado. Se calcula la probabilidad frecuentista para diferentes valores 


```{r eruptions, echo=FALSE}
inputPanel(
  sliderInput("N", label = "N:",
              min = 6, max = 100000, value=10000, step = 10)
)

renderPrint({
dado <- sample(1:6, input$N, replace=TRUE);
dado1<-sum(dado==1);dado2<-sum(dado==2);dado3<-sum(dado==3);
dado4<-sum(dado==4);dado5<-sum(dado==5);dado6<-sum(dado==6);
frec<-c(dado1,dado2,dado3,dado4,dado5,dado6);
frecrel<-frec/input$N;
valores<-data.frame(1:6,frecrel)
names(valores)<-c("Número","Frecuencia Relativa")
valores
})

renderPlot({
dado <- sample(1:6, input$N, replace=TRUE);
dado1<-sum(dado==1);dado2<-sum(dado==2);dado3<-sum(dado==3);
dado4<-sum(dado==4);dado5<-sum(dado==5);dado6<-sum(dado==6);
frec<-c(dado1,dado2,dado3,dado4,dado5,dado6);
frecrel<-frec/input$N;
barplot(frecrel, main="Frecuencia relativa de 1 dado ", 
  	xlab="Número de dado", names.arg=c("1", "2", "3","4", "5", "5"))
})



```



